### PR TITLE
Github Apps-migration of Travis and added additional analysis tools

### PR DESCRIPTION
**Pull request by jvdb**
~~So currently please don't review and/or merge this PR, because the PR itself is part of the work.~~ Checks should be on the `Checks`-tab, Travis should still work after migration to the Github Apps-version (#248) and some new code analysis tools have been enabled (#254).

~~Please interpret the review invitation to provide feedback on if/how it works :)~~

Work is now finished. We've added CodeFactor, Codacy and LGTM as new static analysis tools. Please review so this can be merged.

### CODE REVIEW

**Comment by jvdb** [comment]
Some observations:

1. Travis works really well with the _Checks_-tab! You can even get a view of the configuration and status without leaving Github! Awesome.
2. Codecov shows up on the _Checks_-tab but is stuck in "queued"? Clicking the "re-run" link does nothing but reload the page it seems. Doesn't even reset the queued timer.
3. BetterCodeHub and CodeFactor show up in the _Checks_-list at the bottom of the _Conversation_-tab, but not on the _Checks_-tab. Maybe they don't support that yet? I noticed that they also don't appear in the list of Github Apps.
4. I don't see Codacy and LGMT anywhere? They should be enabled.

**Comment by rdvdijk** [comment]
The Checks-tab looks pretty cool. I was hoping that Codecov would work now, but it's still "queued" after 10 hours. We might have to do some Googling/Stackoverflowing to figure out why the other checks aren't working (yet).

**Comment by jvdb** [comment]
Codacy now shows up in the bottom list too! But also not on the _Checks_-tab, basically same as BetterCodeHub and CodeFactor.

**Comment by jvdb** [comment]
LGMT is there now as well. Turns out I had to enable a webhook.

**Pull request merged**
