### PR TITLE
Def and Until tokens should not allow empty name

### PR DESCRIPTION
**Pull request by rdvdijk**
This is because a `ParseValue` with an empty name leads to `matches()` anomalies.

```java
    public boolean matches(final String name) {
        return this.name.equals(name) || this.name.endsWith(Token.SEPARATOR + name);
    }
```

### CODE REVIEW

**Comment by jvdb** [comment]
Why did codecov comment twice?

**Comment by rdvdijk** [comment]
@jvdb Maybe because I made a 2nd comment (typo fix)?

**Comment by jvdb** [comment]
@rdvdijk Normally it edits its own comments to update it... Its second comment here was also edited. Probably just lost track of the first one somehow :-)

**Comment by rdvdijk** [comment]
I deleted the first one.

**Pull request merged**
